### PR TITLE
Added memory-game to repositories list

### PR DESCRIPTION
**Pull request by cmcrawford2**
---
## 📢 Only PRs from existing Virtual Coffee members will be accepted.
---

## Type of Contribution

Check the item(s) that applies.

- [ ] 🌱 Practice Open Source
- [x] 📃 Repositories List

### If your type of contribution is Repositories List, check items in the repository checklist below that apply.

⚠️ _We only accept PRs where most of the items are checked_

- [x] Relevant name
- [x] Description
- [x] Relevant tags
- [x] README.md file
- [x] CONTRIBUTIONS.md/CONTRIBUTING.md file
- [x] Open source license
- [x] Code of Conduct (COC)
- [ ] Issue and Pull Request templates

### CODE REVIEW

**Comment by adiati98** [comment]
Hey @cmcrawford2,
Thanks for the PR! We've merged a PR before yours. So please resolve the conflicts before we can merge this.

**Comment by cmcrawford2** [comment]
Hi Ayu!

I tried using the resolve conflicts button in the virtual-coffee/vc-preptember repository, but all I see is this:

...
- [Django link-in-bio tool](https://github.com/Terieyenike/linktree)
<<<<<<< main
- [Classic Memory Game](https://github.com/cmcrawford2/memory-game)
=======
>>>>>>> main
...

I’m not sure what to do, because [Django link-in-bio tool] was already in the file that I submitted.
Can you tell me what to do? Otherwise I’ll sync my forked repository and start over.

Cris

**Comment by adiati98** [comment]
Hey @cmcrawford2,

So this is what you have:

```markdown
- [Django link-in-bio tool](https://github.com/Terieyenike/linktree)
<<<<<<< main
- [Classic Memory Game](https://github.com/cmcrawford2/memory-game)
=======
```

You can delete the conflicts marker, so it would be as below to resolve the conflict:

```markdown
- [Django link-in-bio tool](https://github.com/Terieyenike/linktree)
- [Classic Memory Game](https://github.com/cmcrawford2/memory-game)
```

**Comment by cmcrawford2** [comment]
Hi!
I made the change. I'm still puzzled why the change I made looks just like the file I originally submitted.
Cris

**Review by adiati98 — APPROVED** [review]
Thank you, @cmcrawford2! 

Thank you GIF

**Comment by adiati98** [comment]
@cmcrawford2 it was because one PR that I merged before yours.
They added a repo before "Forem".
So the order of the list changed. Forem, Django, and your repo moved down by one line.
And you haven't have this new change in your file before you updated.

**Comment by cmcrawford2** [comment]
OK! I didn't notice. Glad it worked out!

Cris

**Pull request merged**
