### PR TITLE
Added cris crawford

### PR DESCRIPTION
**Pull request by cmcrawford2**
---
## 📢 Only PRs from existing Virtual Coffee members will be accepted.
---

## Type of Contribution

Check the item(s) that applies.

- [x] 🌱 Practice Open Source
- [ ] 📃 Repositories List

### If your type of contribution is Repositories List, check items in the repository checklist below that apply.

⚠️ _We only accept PRs where most of the items are checked_

- [ ] Relevant name
- [ ] Description
- [ ] Relevant tags
- [ ] README.md file
- [ ] CONTRIBUTIONS.md/CONTRIBUTING.md file
- [ ] Open source license
- [ ] Code of Conduct (COC)
- [ ] Issue and Pull Request templates

### CODE REVIEW

**Comment by dominicduffin1** [comment]
Hi @cmcrawford2! Thank you for your contribution! We've merged another PR before yours so can you please resolve the merge conflict so we can merge yours?

**Comment by cmcrawford2** [comment]
Hi!
When I type "git pull" it says "already up to date." What do I need to do
to get to the merge conflict?
Cris

**Comment by cmcrawford2** [comment]
Wait I understand, "git pull" looks at my forked repo. Do I need to fork
again?

Cris

**Comment by adiati98** [comment]
Hey @cmcrawford2, you don't need to fork again.

You got "already up to date" because your forked repo on GitHub is not updated yet. So you are basically pulling the same state as when you forked it.

First, you need to update your forked repo on GitHub.
At your forked repo, click the "Sync fork", then "Update branch" button.

Then go to your local working branch and run `git pull origin main`.

Let me know if it's still doesn't work 🙂.

**Comment by cmcrawford2** [comment]
Hi Ayu! I synced the fork (had to do it more than once though). I didn't
see an update branch button. I just edited the file on github, and then
made a pull request (had to click the "create pull request" button about 3
times). I chose the option that created a branch. Then I went back to my
own repo on my laptop and tried git pull origin main. It said it had
unresolved conflicts. So I deleted the participants file and tried again,
and it still gave me that error. I have no idea what to do now. When this
happens to my personal repos, I just delete the entire git structure on my
laptop (.git directory), delete the repository on github, and start from
scratch. I don't really need the repository on my laptop, since I edited
the file in github, but I would like it to work.
Cris

**Comment by cmcrawford2** [comment]
Hi Ayu,
I have another question. If I say from my terminal, "git clone
https://github.com/cmcrawford2/repository" it asks me for username and
password, then tells me that I can't use username and password since August
2022. So I always use SSH. But I see in the video that Dominic had no
problem cloning his repository that way. What am I doing wrong?
Not urgent - I understand if you can't answer.
Cris

**Review by adiati98 — APPROVED** [review]
Hey @cmcrawford2!
I reopened your pull request and it doesn't give any conlict. So I'm merging it in!!!! 🎉 

git merge GIF

**Comment by adiati98** [comment]
> Hi Ayu, I have another question. If I say from my terminal, "git clone https://github.com/cmcrawford2/repository" it asks me for username and password, then tells me that I can't use username and password since August 2022. So I always use SSH. But I see in the video that Dominic had no problem cloning his repository that way. What am I doing wrong? Not urgent - I understand if you can't answer. Cris

@cmcrawford2 using SSH is also fine.
But for you to be able to use the HTPPS as what Dominic did in the video, you need to create a [Personal Access Token](https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/creating-a-personal-access-token) to enter when GitHub prompts your password.

I hope this answers your question :)

**Comment by adiati98** [comment]
Hey @cmcrawford2,
It's true that [GitHub is shutting down Git passwords authentication since 2021](https://github.blog/changelog/2021-08-12-git-password-authentication-is-shutting-down/) and changed it to token-based authentication (personal access token is one of them).

Maybe [this thread](https://github.com/orgs/community/discussions/38705) can help you understand it more.

**Pull request merged**
