### PR TITLE
Feat/add linktree repo

### PR DESCRIPTION
**Pull request by Terieyenike**
---
## 📢 Only PRs from existing Virtual Coffee members will be accepted.
---

## Type of Contribution

Check the item(s) that applies.

- [ ] 🌱 Practice Open Source
- [x] 📃 Repositories List

### If your type of contribution is Repositories List, check items in the repository checklist below that apply.

⚠️ _We only accept PRs where most of the items are checked_

- [x] Relevant name
- [x] Description
- [x] Relevant tags
- [x] README.md file
- [x] CONTRIBUTIONS.md/CONTRIBUTING.md file
- [x] Open source license
- [x] Code of Conduct (COC)
- [ ] Issue and Pull Request templates

## Description

This PR adds LinkPlant repository to the Repositories List.

### CODE REVIEW

**Comment by dominicduffin1** [comment]
Thank you for your contribution @Terieyenike, looks good! As we've merged in a prior contribution before yours, can you please resolve the merge conflict so we can merge yours as well?

**Comment by Terieyenike** [comment]
I am trying to pull the recent changes to resolve the conflict, but I cannot.

@dominicduffin1, do you know how I can resolve this?

error

**Comment by dominicduffin1** [comment]
Hi @Terieyenike! Can you please show the command(s) you are running that gets this error message?

**Comment by Terieyenike** [comment]
I tried @dominicduffin1.

```
git pull upstream main

// OR

git pull origin main
```

**Comment by danieltott** [comment]
@Terieyenike in GitHub (not the command line), you should see a "Resolve conflicts" button in the PR:

image

Hit that, and you'll see GitHub's conflict resolver tool.

image

You can see here there are two commits trying to edit the same line.

Since in this situation we want to keep both, you can remove the conflict markers and leave both new lines in there. It might be technically correct for you to put yours after the existing one (the Forem one in this case). Something like this:

image


After you do that, you can hit the "Mark as Resolved" button and then you should be able to move forward.

**Comment by Terieyenike** [comment]
Thanks, @danieltott and @dominicduffin1 for your help. 

I think I have fixed the conflict.

**Review by dominicduffin1 — APPROVED** [review]

**Comment by dominicduffin1** [comment]
Thank you @Terieyenike! Looks good. Merging now.

**Pull request merged**
